name = "main"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
gladvent = ">= 2.0.2 and < 3.0.0"
gtempo = ">= 5.0.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2023.1]
pt_1 = 56397
pt_2 = 55701

[gladvent.2024.1]
pt_1 = 1223326
pt_2 = 21070419

[gladvent.2024.2]
pt_1 = 390
pt_2 = 439

[gladvent.2024.3]
pt_1 = 170068701
# pt_2 = 